name: CVI Calculation and Dashboard Update

on:
  schedule:
    - cron: '*/15 * * * *'   # frequent runs (Deribit + cached/series-based fallbacks)
    - cron: '5 * * * *'      # once per hour, allow CoinGecko
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: cvi-scrape
  cancel-in-progress: true

jobs:
  fetch-options-data:
    runs-on: ubuntu-latest
    env:
      CVI_EXCLUDE: ""              # no skip by default
      CVI_INCLUDE: ""              # optional include list
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      # Default: we’ll set COINGECKO_MODE in the next step via $GITHUB_ENV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bootstrap manifest on first run
        run: |
          mkdir -p docs
          [ -f docs/cvi_manifest.json ] || echo '{"assets":[]}' > docs/cvi_manifest.json

      - name: Decide CoinGecko mode based on schedule
        run: |
          # If this run was triggered by the hourly cron ('5 * * * *'), enable CoinGecko.
          if [ "${{ github.event_name }}" = "schedule" ] && [ "${{ github.event.schedule }}" = "5 * * * *" ]; then
            echo "COINGECKO_MODE=on" >> "$GITHUB_ENV"
            echo "CoinGecko: ON (hourly refresh)"
          else
            echo "COINGECKO_MODE=off" >> "$GITHUB_ENV"
            echo "CoinGecko: OFF (15-min run uses Deribit + fallbacks)"
          fi

      - name: Set up Node.js (no cache, first-run friendly)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create package-lock.json if missing
        if: ${{ hashFiles('package-lock.json') == '' }}
        run: npm install --package-lock-only --ignore-scripts --no-audit --no-fund

      - name: Set up Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --ignore-scripts --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Build CVI data for all assets
        run: node scripts/fetchOptionsData.js

      - name: Generate ERI + trade recommendations
        run: node scripts/strategyEngine.js

      - name: Commit and push changes (only if there are changes)
        uses: EndBug/add-and-commit@v9
        with:
          add: docs/**
          message: "Update CVI + ERI: smiles, timeseries, manifest, signals, risk index, orders + meta"
          default_author: github_actions
