name: CVI Calculation and Dashboard Update

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  push:
    branches: [ main ]       # also on pushes to main

jobs:
  fetch-options-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fetch options + build CVI
        run: npm run start

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/cvi.json docs/cvi_timeseries.json"
          message: "Update CVI smile & timeseries"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
