name: CVI Calculation and Dashboard Update

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  push:
    branches: [ main ]

permissions:
  contents: write

# avoid overlapping runs
concurrency:
  group: cvi-scrape
  cancel-in-progress: true

jobs:
  fetch-options-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm i

      - name: Build CVI data for all assets
        run: node scripts/fetchOptionsData.js

      # Ensure manifest exists even on a totally fresh repo
      - name: Bootstrap manifest on first run
        run: |
          mkdir -p docs
          [ -f docs/cvi_manifest.json ] || echo '{"assets":[]}' > docs/cvi_manifest.json

      - name: Commit and push changes (only if there are changes)
        uses: EndBug/add-and-commit@v9
        with:
          add: docs/**
          message: "Update CVI (multi-asset): smile + timeseries + manifest + signals"
          default_author: github_actions
