name: CVI Calculation and Dashboard Update

on:
  schedule:
    - cron: '*/30 * * * *'   # runs every 30 minutes (UTC)
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: cvi-scrape
  cancel-in-progress: true

jobs:
  fetch-options-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      # Make sure docs/ exists on very first run so the commit step always has a target
      - name: Bootstrap docs/ + manifest on first run
        run: |
          mkdir -p docs
          [ -f docs/cvi_manifest.json ] || echo '{"assets":[]}' > docs/cvi_manifest.json

      - name: Build CVI data for all assets
        run: node scripts/fetchOptionsData.js

      - name: Commit and push changes (only if there are changes)
        uses: EndBug/add-and-commit@v9
        with:
          add: docs/**
          message: "Update CVI (multi-asset): smile + timeseries + manifest + signals"
          default_author: github_actions
