name: CVI Calculation and Dashboard Update

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  fetch-options-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Fetch options data
        run: |
          npm run start  # This will run the script to fetch the data and create/update cvi.json

      - name: Check if cvi.json exists and is updated
        run: |
          if [ -f docs/cvi.json ]; then
            echo "cvi.json exists, committing changes."
          else
            echo "cvi.json does not exist, creating file."
            touch docs/cvi.json
          fi

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v8
        with:
          message: 'Update CVI data'
          add: 'docs/cvi.json'
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          committer_name: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
