name: Train and Evaluate Forecasts

on:
  schedule:
    - cron: '15 6 * * *' # daily at 06:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: train-evaluate
  cancel-in-progress: false

jobs:
  train-evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Node deps
        run: npm ci

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Backfill features (daily)
        run: npm run backfill
        env:
          COINGECKO_PLAN: ${{ secrets.COINGECKO_PLAN }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}

      - name: Train and produce forecasts
        run: npm run train

      - name: Evaluate forecasts
        run: npm run evaluate

      - name: Validate docs
        run: npm run validate

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: daily train/evaluate update"
            git push
          fi
